version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: hotio/qbittorrent:release-5.0.1@sha256:53530bb04f69ea02903367636c32f796795677eca276231cf52f9a968e55c9cf
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      # /app/qBittorrent/downloads is the default path set in qBittorrent
      - ${UMBREL_ROOT}/data/storage/downloads:/app/qBittorrent/downloads
    restart: on-failure