version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: rotki_web_1
      APP_PORT: 80

  web:
    image: rotki/rotki:v1.36.0@sha256:765cd6cebfc25a2e0ddbe5735674e655b81a1a19ab7c207f2dfcd34428ad8d3a
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/data:/data
      - ${APP_DATA_DIR}/data/logs:/logs