version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mealie_web_1
      APP_PORT: 9000
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: ghcr.io/mealie-recipes/mealie:v2.2.0@sha256:ea53ca0e874cf30c3e6bbed35f5a01a029bafb602d050ddd584fdb7defdb6f8a
    restart: on-failure
    environment:
      # Allow additional user sign-up without token
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
    volumes:
      - ${APP_DATA_DIR}/data:/app/data