version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vaultwarden_server_1
      APP_PORT: 8089
      PROXY_AUTH_ADD: "false"

  server:
    image: vaultwarden/server:1.32.4@sha256:7271b8ceb729f9b46144c800125813dcc8d16bb6874217c48e59b22b45e47d7d
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ROCKET_PORT: 8089