version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.11.85@sha256:cbef42b8c8e80e0413e5d4d47af479ed47d3682da68af8edf23daf17671e2c8f
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m